# Generated by Django 3.1.7 on 2023-02-21 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230212_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipedrive_jsondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=50)),
                ('Data', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='I_P',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 11, 23, 23, 377462)),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 11, 23, 23, 372465)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 11, 23, 23, 309508)),
        ),
    ]
