# Generated by Django 3.1.7 on 2023-03-01 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230301_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedrive_jsondata',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 26, 8, 722983)),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 26, 8, 718985)),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 26, 8, 723983)),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='investment_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='sender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 26, 8, 663017)),
        ),
    ]
