# Generated by Django 3.1.7 on 2023-03-01 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230301_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 30, 16, 931632)),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 30, 16, 928633)),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 30, 16, 932632)),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pipedrive_jsondata',
            name='sender',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 13, 30, 16, 878378)),
        ),
    ]
