# Generated by Django 4.0.1 on 2023-01-09 06:06

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20230105_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', tinymce.models.HTMLField()),
                ('content', tinymce.models.HTMLField()),
                ('desc', models.TextField(default='')),
                ('city', models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford'), ('9', 'preston'), ('10', 'nottingham')], max_length=20)),
                ('image_1', models.FileField(upload_to='media/blogs')),
                ('image_2', models.FileField(upload_to='media/blogs')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 1, 9, 11, 36, 49, 301943))),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='deposited_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 11, 36, 49, 299942)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford'), ('9', 'preston'), ('10', 'nottingham')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 11, 36, 49, 283927)),
        ),
    ]
