# Generated by Django 4.0.1 on 2023-01-09 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_blogs_properties_deposited_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title_t',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 18, 35, 6, 354237)),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 18, 35, 6, 352235)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 18, 35, 6, 337222)),
        ),
    ]
