# Generated by Django 4.0.1 on 2023-01-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_blogs_title_t_alter_blogs_pub_date_and_more'),
        ('home', '0036_auto_20230109_1236'),
    ]

    operations = [
    ]
