"""
Django settings for lpc project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1&ppfk9nu#6neygjbp61d1bmkiz*1*^h7_ud_%ugd9w96v@0_z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    # 'django_summernote',
    'tinymce',
    # 'crispy_forms',
    'corsheaders',

]
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
'corsheaders.middleware.CorsMiddleware',
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOWED_ORIGINS = [
#     "https://ads.lpcinvest.com",
#     "http://localhost:8080",
#     "http://127.0.0.1:8000",
# ]
from .DEFAULTS import DEFAULT_HEADERS

CORS_ALLOW_HEADERS = DEFAULT_HEADERS 
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'lpc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.views.common',
            ],
        },
    },
]

WSGI_APPLICATION = 'lpc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = { 'default': { 'ENGINE': 'django.db.backends.mysql',
                                'NAME': 'db2',
                                'USER': 'lpcinvestadmin',
                                'HOST':'db2.coy3lmfl9bor.ap-northeast-1.rds.amazonaws.com',
                                'PORT':'3306',
                                'PASSWORD':'lpcINVEST',
                                } }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# SMTP CONFIG
SMTP_HOST= str(os.getenv('SMTP_HOST'))
SMTP_HOST_USER = str(os.getenv('SMTP_HOST_USER'))
SMTP_HOST_PASS = str(os.getenv('SMTP_HOST_PASS'))
SMTP_HOST_PORT = str(os.getenv('SMTP_HOST_PORT'))
EMAIL_USE_TLS = True  

EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_HOST_USER = 'privatemale67@gmail.com'  
EMAIL_HOST_PASSWORD = 'wxikzwcmpyqoltcv'  
EMAIL_PORT = 587  
STATIC_URL = '/static/'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'



MESSAGE_TAGS = {
    messages.ERROR:'danger'
}


STATIC_URL = '/static/'

STATICFILES_DIRS = [
os.path.join(BASE_DIR, 'static')
]
MEDIA_ROOT= os.path.join(BASE_DIR, "media")
MEDIA_URL="/media/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
X_FRAME_OPTIONS = 'SAMEORIGIN'

AUTH_USER_MODEL = 'home.CustomUser'
AUTHENTICATION_BACKENDS = ['home.backends.EmailBackend'] # new


